### ISSUE TITLE
Automate builds and publish signed builds to Play store

### ISSUE THREAD

**Issue by abbyad** [medic/rdt-capture#16]
Follow up to https://github.com/medic/medic-projects/issues/6195 (request to build and publish new version), we should automate the signing and publishing of builds to the Play store.

Worth considering this alongside https://github.com/medic/medic-collect/issues/27 and https://github.com/medic/medic-gateway/issues/145.

**Comment by kennsippell** [comment]
I started working on this ticket yesterday, but experienced some road blocks getting unit tests to pass + getting this to build locally (and in Travis). I am running `./gradlew test` and `./gradlew assemble` for this.

The first error I see is: `No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android` I've solved this locally by upgrading the gradle wrapper to `3.3.2`, since this is a deprecated ABI.

The next error I'm seeing is:

```
> Android resource linking failed
  /home/kenn/rdt-capture/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml:4: AAPT: error: resource mipmap/ic_launcher_foreground (aka edu.washington.cs.ubicomplab.rdt_reader:mipmap/ic_launcher_foreground) not found.
      
  /home/kenn/rdt-capture/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml:4: AAPT: error: resource mipmap/ic_launcher_foreground (aka edu.washington.cs.ubicomplab.rdt_reader:mipmap/ic_launcher_foreground) not found.
      
  error: failed linking file resources.
```

I'm wondering if these issues are bugs, if they have been fixed elsewhere, or maybe you use a different script to build this project? @cjpark87

**Comment by cjpark87** [comment]
Hi Kenn. Unfortunately, I don't have a good answer to your questions :( 

I wasn't involved in releasing this app into Play Store. All of the releases to Play Store have done by Medic Mobile. I think someone in your team might have more experience and a better understanding of how this process works.

I just made an update to the master branch that could resolve the "linking file resources" issue. Let me know the building goes with the new commit.

Thanks!

**Comment by kennsippell** [comment]
Thanks for that fix! I am able to build locally now. Just wanting to make sure there wasn't some more elaborate build process for repo. 

I'll include you on the pull request to automate the build.
